---

- name: Create a new user
  ansible.builtin.user:
    name: "{{ username  }}"
    shell: "{{ user_shell | default('/bin/bash') }}"
    groups: "{{ user_groups | default('root') }}"
    state: present
  tags: create_user
